# Generated by shunter/scripts/formula.mjs. Do not edit by hand.
class Shunter < Formula
  desc "Route coding tasks to the cheapest capable model using TypeSafe Jev"
  homepage "https://github.com/cruxdigital-llc/homebrew-tools"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/cruxdigital-llc/homebrew-tools/releases/download/v0.1.0/shunter-0.1.0-darwin-arm64.tar.gz"
      sha256 "9d00ecabdfa5aaa6faca2bcf3881736a283a3f81a36c8c3063b811fb0075eea8"
    end
    on_intel do
      url "https://github.com/cruxdigital-llc/homebrew-tools/releases/download/v0.1.0/shunter-0.1.0-darwin-x64.tar.gz"
      sha256 "9bf3a90dbc1a26ade08607258230ca87420baa9bba7f517571fd44c744bade12"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cruxdigital-llc/homebrew-tools/releases/download/v0.1.0/shunter-0.1.0-linux-arm64.tar.gz"
      sha256 "29f66af5c70424ee8fd5133f3340654eb10e30415877c647460887b543490bd7"
    end
    on_intel do
      url "https://github.com/cruxdigital-llc/homebrew-tools/releases/download/v0.1.0/shunter-0.1.0-linux-x64.tar.gz"
      sha256 "8e5c0a842a556fa44b19e3bab0de162b54cefddbabf15f2f622e25fbf8f91c98"
    end
  end

  def install
    bin.install "shunter"
  end

  def caveats
    <<~EOS
      Run `shunter` in any project. The first run walks you through adding
      your TypeSafe (Jev) and OpenRouter API keys, or run `shunter setup`.

      Keys and settings live in ~/.config/shunter (not touched by brew).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shunter --version")
  end
end
