# Generated by shunter/scripts/formula.mjs. Do not edit by hand.
class Shunter < Formula
  desc "Route coding tasks to the cheapest capable model using TypeSafe Jev"
  homepage "https://github.com/cruxdigital-llc/homebrew-shunter"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/cruxdigital-llc/homebrew-shunter/releases/download/v0.1.0/shunter-0.1.0-darwin-arm64.tar.gz"
      sha256 "40f056b0d9e598ab3197842cd20492a1958a641d95370693921d66548f592536"
    end
    on_intel do
      url "https://github.com/cruxdigital-llc/homebrew-shunter/releases/download/v0.1.0/shunter-0.1.0-darwin-x64.tar.gz"
      sha256 "429cda59e306ae9cde27029f46291585d36a51730bbdd68ff403f5d915bb7c41"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cruxdigital-llc/homebrew-shunter/releases/download/v0.1.0/shunter-0.1.0-linux-arm64.tar.gz"
      sha256 "e1253832479ce253c5f14aea6691e0613e1e6b7766c501aa269b6285caea19ce"
    end
    on_intel do
      url "https://github.com/cruxdigital-llc/homebrew-shunter/releases/download/v0.1.0/shunter-0.1.0-linux-x64.tar.gz"
      sha256 "1d21ab81ecfa9b203852953aa9e18668f7fa08fa8f43e9c5706e28ccf5935da9"
    end
  end

  def install
    bin.install "shunter"
  end

  def caveats
    <<~EOS
      Run `shunter` in any project. The first run walks you through adding
      your TypeSafe (Jev) and OpenRouter API keys, or run `shunter setup`.

      Keys and settings live in ~/.config/shunter (not touched by brew).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shunter --version")
  end
end
